#!/usr/bin/python3

import sys, os, types, inspect
from settings import config
from context import test_context
from tool_box import *
from set_up import set_up
from mount_union import mount_union
from unmount_union import unmount_union
from remount_union import remount_union
from direct import direct_open_file, direct_fs_op

def show_format(why):
    if why:
        print(why)
    print("Format:")
    print("\t", sys.argv[0], "<--no|--ov|--ovov>[=<maxlayers>] [--fuse=<subtype>] [--samefs|--maxfs=<maxfs>|--squashfs] [--xdev] [--xino] [--meta] [--verify] [--ts=<0|1>] [-v] [<test-name>+]")
    print("\t", sys.argv[0], "<--no|--ov|--ovov> [--fuse=<subtype>] [--samefs|--squashfs] [-s|--set-up]")
    print("\t", sys.argv[0], "--open-file <file> [-acdertvw] [-W <data>] [-R <data>] [-B] [-E <err>]")
    print("\t", sys.argv[0], "--<fsop> <file> [<args>*] [-aLlv] [-R <content>] [-B] [-E <err>]")
    sys.exit(2)

if len(sys.argv) < 2:
    show_format("Insufficient arguments")

cfg = config(sys.argv[0])
args = sys.argv[1:]

###############################################################################
#
# Handle requests to perform single probes
#
###############################################################################
if args[0] == "--open-file":
    try:
        direct_open_file(cfg, args[1:])
    except ArgumentError as ae:
        show_format(str(ae))
    except TestError as te:
        exit_error(str(te))
    sys.exit(0)

if (args[0] == "--chmod" or
    args[0] == "--link" or
    args[0] == "--mkdir" or
    args[0] == "--readlink" or
    args[0] == "--rename" or
    args[0] == "--rmdir" or
    args[0] == "--truncate" or
    args[0] == "--unlink" or
    args[0] == "--utimes"):
    try:
        direct_fs_op(cfg, args)
        sys.exit(0)
    except ArgumentError as ae:
        show_format(str(ae))
    except TestError as te:
        exit_error(str(te))
    sys.exit(0)

###############################################################################
#
# Unmount old attempts
#
###############################################################################
try:
    while True:
        system("umount " + lower_mntroot)
except:
    pass

try:
    while True:
        system("umount " + upper_mntroot)
except:
    pass

try:
    while True:
        system("umount " + union_mntroot)
except:
    pass

###############################################################################
#
# Work out the test parameters
#
###############################################################################
recycle_list = [ "" ]
maxlayers = 0
if args[0] == "--no":
    cfg.set_testing_none()
elif args[0].startswith("--ov"):
    cfg.set_testing_overlayfs()
    if args[0].startswith("--ovov"):
        cfg.set_nested()
    s = args[0]
    i = s.rfind("=")
    if i >= 0:
        n = s[i+1:]
        recycle_list = [ n, "" ]
        maxlayers = int(n)
        if maxlayers < 0:
            show_format("Invalid value for maxlayers >= 0")
else:
    show_format("Invalid test type selector (--ov or --no)")
args = args[1:]

if len(args) > 0 and args[0].startswith("--fuse="):
    if not cfg.testing_overlayfs() or cfg.is_nested:
        show_format("--fuse requires --ov")
    s = args[0]
    t = s[s.rfind("=")+1:]
    cfg.set_fusefs(t)
    args = args[1:]

if cfg.testing_none():
    index = None
    xino_auto = None
    redirect_dir = None
    metacopy = None
elif cfg.is_fusefs():
    # Don't check kernel module params for FUSE test and assume the following
    # defaults, because user can disable redirect_dir with --xdev and user can
    # enable index and xino with --verify
    index = False
    xino_auto = False
    redirect_dir = True
    metacopy = False
elif cfg.testing_overlayfs():
    index = check_bool_modparam("index")
    xino_auto = check_bool_modparam("xino_auto")
    redirect_dir = check_bool_modparam("redirect_dir")
    # Overlayfs feature "redirect_dir" can be enabled with kernel version >= v4.10.
    # Otherwise, overlayfs tests should skip rename tests that would result in EXDEV.
    if redirect_dir is False:
        cfg.add_mntopt("redirect_dir=on")
        redirect_dir = True
    # xino can be enabled with kernel version >= v4.17
    if xino_auto is True:
        cfg.add_mntopt("xino=on")
        cfg.set_xino()
    # metacopy can be enabled with kernel version >= v4.19
    metacopy = check_bool_modparam("metacopy")
    if metacopy is True:
        cfg.set_metacopy()

# maxfs 0 means one upper fs and one lower fs
maxfs = 0
if len(args) > 0 and (args[0] == "--samefs" or args[0] == "--squashfs" or args[0].startswith("--maxfs=")):
    if args[0] == "--samefs":
        # maxfs < 0 means samefs
        maxfs = -1
    elif args[0] == "--squashfs":
        cfg.set_squashfs()
    elif args[0].startswith("--maxfs="):
        s = args[0]
        n = s[s.rfind("=")+1:]
        maxfs = int(n)
        if maxfs < 0:
            show_format("Invalid value for maxfs >= 0")
    args = args[1:]
cfg.set_maxfs(maxfs)

# We might be being asked to just set up and then leave without doing
# any further testing.
if len(args) > 0 and ( args[0] == "-s" or args[0] == "--set-up" ):
    if len(args) > 1:
        show_format("Too many arguments for --set-up")
    ctx = test_context(cfg)
    set_up(ctx)
    mount_union(ctx)
    sys.exit(0)

termslash = "0"
while len(args) > 0 and args[0].startswith("-"):
    if args[0] == "-v":
        cfg.set_verbose()
    elif args[0] == "--ts=0":
        termslash = "0"
    elif args[0] == "--ts=1":
        termslash = "1"
    elif args[0] == "--xdev":
        # Disable "redirect_dir" and skip dir rename tests
        if redirect_dir is True:
            cfg.add_mntopt("redirect_dir=off")
            redirect_dir = False
    elif args[0] == "--xino":
        if xino_auto is None:
            print("xino not supported - ignoring --xino")
        else:
            cfg.add_mntopt("xino=on")
            cfg.set_xino()
    elif args[0] == "--meta":
        if metacopy is None:
            print("metacopy not supported - ignoring --meta")
        else:
            cfg.add_mntopt("metacopy=on")
            cfg.set_metacopy()
    elif args[0] == "--verify":
        cfg.set_verify()
        if index is False:
            cfg.add_mntopt("index=on")
    else:
        show_format("Invalid flag " + args[0])
    args = args[1:]

###############################################################################
#
# Work out the list of tests to run
#
###############################################################################
tests = [
    "open-plain",
    "open-trunc",
    "open-creat",
    "open-creat-trunc",
    "open-creat-excl",
    "open-creat-excl-trunc",
    "noent-plain",
    "noent-trunc",
    "noent-creat",
    "noent-creat-trunc",
    "noent-creat-excl",
    "noent-creat-excl-trunc",
    "sym1-plain",
    "sym1-trunc",
    "sym1-creat",
    "sym1-creat-excl",
    "sym2-plain",
    "sym2-trunc",
    "sym2-creat",
    "sym2-creat-excl",
    "symx-plain",
    "symx-trunc",
    "symx-creat",
    "symx-creat-excl",
    "symx-creat-trunc",
    "truncate",
    "dir-open",
    "dir-weird-open",
    "dir-open-dir",
    "dir-weird-open-dir",
    "dir-sym1-open",
    "dir-sym1-weird-open",
    "dir-sym2-open",
    "dir-sym2-weird-open",
    "readlink",
    "mkdir",
    "rmdir",
    "rmtree",
    "rmtree-new",
    "hard-link",
    "hard-link-dir",
    "hard-link-sym",
    "unlink",
    "rename-file",
    "rename-hard-link",
    "rename-new-dir",
    "rename-new-pop-dir",
    "rename-mass",
    "rename-mass-2",
    "rename-mass-3",
    "rename-mass-4",
    "rename-mass-5",
    "rename-mass-dir",
    "rename-mass-sym",
    "impermissible"
    ]

# For backward compat with kernel version < v4.10 or with flag --xdev,
# run an alternative test to verify EXDEV behavior. Otherwise, run all
# directory rename tests.
if cfg.testing_overlayfs() and not redirect_dir:
    tests += [
        "rename-exdev",
        ]
else:
    tests += [
        "rename-dir",
        "rename-empty-dir",
        "rename-pop-dir",
        "rename-move-dir",
        ]

if len(args) > 0:
    tests = args

if cfg.testing_overlayfs():
    if cfg.is_nested():
        test_what = "--ovov"
    else:
        test_what = "--ov"
else:
    test_what = "--no"

for test in tests:
    for recycle in recycle_list:
        test_how = test_what
        if recycle != "":
            test_how = test_what + "=" + str(maxlayers)
        if cfg.testing_overlayfs():
            if maxfs > 0:
                test_how += " --maxfs=" + str(maxfs)
            elif maxfs < 0:
                test_how += " --samefs"
        msg = cfg.progname() + " " + test_how + " --ts=" + termslash + " " + test
        print("***");
        print("***", msg);
        print("***");
        if cfg.is_verbose():
            write_kmsg(msg);

        ctx = test_context(cfg, termslash == "1", False, recycle != "", maxlayers)

        # Construct the union
        set_up(ctx)
        mount_union(ctx)
        os.sync()

        # Run a test script
        script = __import__("tests." + test, globals(), locals(), ['subtests'])
        try:
            subtests = []
            for name in dir(script):
                if not name.startswith("subtest_"):
                    continue
                subtest = getattr(script, name)
                if type(subtest) != types.FunctionType:
                    continue
                subtests.append((inspect.getfile(subtest),
                                 inspect.getsourcelines(subtest)[1],
                                 subtest.__doc__,
                                 subtest))

            # Perform the subtests in the order they're defined in the file
            for (f, line, doc, func) in sorted(subtests, key=lambda s: s[1]):
                ctx.begin_test(f, line, doc)
                func(ctx)

        except TestError as te:
            exit_error(str(te))

        # Stop if the kernel is now tainted
        check_not_tainted()

        # Make sure that all dentries and inodes are correctly released
        unmount_union(ctx)
        del ctx

# Leave the union mounted for further playing
ctx = test_context(cfg)
set_up(ctx)
mount_union(ctx)
